name: "Update YAML Tags"
description: "Updates specified YAML paths with a given tag in a YAML file and commits the changes"
inputs:
  tag:
    description: "Tag to update in YAML files"
    required: true
  yaml-paths:
    description: "List of YAML paths to update (comma-separated)"
    required: true
  file-path:
    description: "Path to the YAML file to update"
    required: true
  repository:
    description: "git repository where to run the upgrade"
    required: true
  branch-name:
    description: "branch name where to commit the changes"
    required: true
  git-release-bot-email:
    description: "Email for the Git release bot"
    required: true
  git-release-bot-name:
    description: "Name for the Git release bot"
    required: true
  gpg-enabled:
    description: "Enable GPG signing (true or false)"
    required: false
    default: "false"
  gpg-key-id:
    description: "GPG key ID for signing commits"
    required: false
  gpg-key:
    description: "GPG private key (base64 encoded)"
    required: false
  ssh-private-key:
    description: "SSH private key for repository access"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.tag }}
    - ${{ inputs.yaml_paths }}
    - ${{ inputs.file_path }}
    - ${{ inputs.branch-name }}
  env:
    GIT_RELEASE_BOT_EMAIL: ${{ inputs.git-release-bot-email }}
    GIT_RELEASE_BOT_NAME: ${{ inputs.git-release-bot-name }}
    GPG_ENABLED: ${{ inputs.gpg-enabled }}
    GPG_KEY_ID: ${{ inputs.gpg-key-id }}
    GPG_KEY: ${{ inputs.gpg-key }}
    SSH_PRIVATE_KEY: ${{ inputs.ssh-private-key }}
    REPO: ${{ inputs.repository }}
    BRANCH_NAME: ${{ inputs.branch-name }}
